### PR TITLE
[QA] NS-755: Increases instance size to m5.large

### PR DESCRIPTION
**Pull request by lyttam**
https://jira.ets.berkeley.edu/jira/browse/NS-755

master PR: #623

### CODE REVIEW

**Comment by lyttam** [comment]
I imagine this will cost extra, but qa workers spin up for only 4 hours (vs 8 hours on dev).

**Comment by lyttam** [comment]
Also maybe @paulkerschen should merge this one so it doesn't interfere with his testing on nessie-qa.

**Comment by paulkerschen** [comment]
Per conversation with @lyttam, we're going to hold off on this for the moment to see how nightly jobs run without an instance upgrade.

**Comment by paulkerschen** [comment]
Turns out we need the bigger guns.

**Pull request merged**
