### PR TITLE
NS-291 Add more CoE student attributes

### PR DESCRIPTION
**Pull request by raydavis**
https://jira.ets.berkeley.edu/jira/browse/NS-291

### CODE REVIEW

**Comment by johncrossman** [comment]
Looks good, @raydavis  Our pesky linter wants a comma.

**Comment by paulkerschen** [comment]
@raydavis It looks like the test-only version of this table (defined in `/fixtures/students.sql`) isn't raising a fuss about missing the new columns because our test coverage is still so spotty. But in hopes of someday, somehow filling these tests out, should we have the fixture keep pace?

**Comment by raydavis** [comment]
Thanks, @johncrossman . As often happens, I fixed `tox` locally and then forgot to push the fix to GitHub.

@paulkerschen , I noticed that `{redshift_schema_coe}.students` fixture SQL seemed to define VARCHAR column types where the real derived-table has Boolean. Was that intended?

**Comment by paulkerschen** [comment]
@raydavis Not intended! Probably that fixture was erroneously copied from the external rather than the internal schema.

**Comment by raydavis** [comment]
Thank, @paulkerschen , I'll amend while I'm in there.

**Comment by raydavis** [comment]
PR amended, @paulkerschen and/or @johncrossman

**Pull request merged**
